### ISSUE TITLE
from __future__ import absolute_import

### ISSUE THREAD

**Issue by nooperpudd** [lovelylain/pyctp#17]
if have define a function as 

``` python

from os import path as init 

def init():
    pass
```

do u understand what the side effect about the same define function names in two different method?

**Comment by sth4nth** [comment]
@nooperpudd, if you found a bug, you can post the code to reproduce the bug rather than just think that there should be a bug. Better yet, this code is simple enough for you to do a fix yourself then fire a pull request. At least it would be better than simply complain and show no evidence.
