### ISSUE TITLE
lovelaylain，是否可以封装下华宝证券的LTS证券接口？

### ISSUE THREAD

**Issue by zckm** [lovelylain/pyctp#23]
LTS接口为华宝证券专有的证券交易接口，此接口与CTP证券接口非常相似，几乎是个clone版本；只是在CTP证券接口的基础上进行了部分改进，以便支持两融业务。谢谢你的Python封装。
LTS接口在这里：https://github.com/zckm/LTS

**Comment by shiweisi** [comment]
请问有该接口的模拟盘地址和账号吗？
有华宝证券开户相关的联系方式吗？
