### ISSUE TITLE
pyctp 连接交易柜台报错，直接用c++或者boost.python则没有问题

### ISSUE THREAD

**Issue by optrade** [lovelylain/pyctp#38]
Register trading Front....
CThostFtdcUserApiImplBase::OnSessionDisconnected[0x7f51c4000958][924581889][    0]

如果直接写c++调 libthosttraderapi.so则没有问题，不知何解？替换这个libthosttraderapi.so到site-packages/ctp中也是无法连接。

使用boost.python封装连接交易柜台也没有问题。

**Comment by lovelylain** [comment]
贴代码

**Comment by optrade** [comment]
import hashlib, os, sys, tempfile, time
from ctp import ApiStruct
from ctp import  TraderApi
class MyTraderApi(TraderApi):
    def __init__(self,brokerID,userID, password):
        self.requestID = 0
        self.brokerID = brokerID
        self.userID = userID
        self.password = password
        self.Create()
        
    def Create(self):
        dir = b''.join((b'ctp.futures', self.brokerID, self.userID))
        dir = hashlib.md5(dir).hexdigest()
        dir = os.path.join(tempfile.gettempdir(), dir, 'Trader') + os.sep
        if not os.path.isdir(dir): os.makedirs(dir)
        TraderApi.Create(self, os.fsencode(dir) if sys.version_info[0] >= 3 else dir)
        
    def RegisterFront(self, front):
        print("Register trading Front....")
        if isinstance(front, bytes):
            return TraderApi.RegisterFront(self, front)
        for front in front:
            TraderApi.RegisterFront(self, front)
    def OnFrontConnected(self):
        print('On trader Front Connected: Login...')
        req = ApiStruct.ReqUserLogin(
            BrokerID=self.brokerID, UserID=self.userID, Password=self.password)
        self.requestID += 1
        self.ReqUserLogin(req, self.requestID)
        
    def OnRspUserLogin(self, pRspUserLogin, pRspInfo, nRequestID, bIsLast):
        print('OnRspUserLogin:', pRspInfo)
        if pRspInfo.ErrorID == 0:
             # Success
            print('GetTradingDay:', self.GetTradingDay())
        


if __name__ == '__main__':
    tradapi = MyTraderApi(b'XXXX', b'XXXXXXXX', b'XXXXXX')
    tradapi.RegisterFront(b'tcp://210.5.151.227:31205')
    tradapi.Init()

**Comment by lovelylain** [comment]
```python
    api = MyTraderApi(b'xxxx', b'xxxx', b'xxxx')
    api.SubscribePrivateTopic(ApiStruct.TERT_RESUME)
    api.SubscribePublicTopic(ApiStruct.TERT_RESUME)
    api.RegisterFront(b'tcp://xxxx:xxxx')
    api.Init()
```

**Comment by optrade** [comment]
仍抱一样的错，无法连接柜台。

**Comment by lovelylain** [comment]
```python
if __name__ == '__main__':
    api = MyTraderApi(b'xxxx', b'xxxx', b'xxxx')
    api.SubscribePrivateTopic(ApiStruct.TERT_RESUME)
    api.SubscribePublicTopic(ApiStruct.TERT_RESUME)
    api.RegisterFront(b'tcp://xxxx:xxxx')
    api.Init()   #这步调用后会创建一个新线程收发数据，主线程继续往下执行
                    #如果你的主线程啥都不干，可以调用api.Join()把进程控制权完全交给子线程
    try:           #不调用api.Join()的话也必须保证主线程不退出，否则api的所有引用消失就自动回收了
        while 1:#有的实现里没等待子线程没这个循环也不会退出，那是存在内存泄漏风险的，是有bug的
            sys.stdout.write('.')#正确做法就是调用Join()或加这么个循环（建议循环，可以Ctrl+C退出程序）
            time.sleep(1)
    except KeyboardInterrupt:
        pass
```

**Comment by optrade** [comment]
problems solved! thank you very much!!!!!!
