### ISSUE TITLE
32位的linux下编译不成功

### ISSUE THREAD

**Issue by LeShan** [lovelylain/pyctp#40]
提示找不到“CThostFtdcInvestorProductGroupMarginField”等很多类，对比了一下，貌似win和linux64下有这个定义，但是linux32下没有，是否版本不同导致的？

**Comment by lovelylain** [comment]
linux32的编译用 commit 1e114f0cdbd728441c345e2878ec50976f7e3e53 及之前的提交，后面升级了api版本，新版本只提供了linux64没提供linux32，不过即使能编译成功，linux32的api在运行时也是有问题的，总之可以认为ctp api不支持linux32.

**Comment by LeShan** [comment]
明白了
