### ISSUE TITLE
CTP断开连接有日志

### ISSUE THREAD

**Issue by morganw** [lovelylain/pyctp#41]
你好，在命令行的情况下，CTP断开连接的时候，有CThostFtdcUserApiImplBase::OnSessionDisconnected[0x7ffd380008c8][-2081292287][    0]，听说CTP c/c++已经去掉了，请问pyctp是否封装的最新的版本？

**Comment by lovelylain** [comment]
https://github.com/lovelylain/pyctp/blob/master/futures/api/version.txt

**Comment by morganw** [comment]
哦，我在一个群里看到现在最新的ctp已经是6.3.6版本了吧？或者在linux64: v6.2.5_20140811
 版本里，在断开连接的时候，如何能去掉CThostFtdcUserApiImplBase::OnSessionDisconnected[0x7ffd380008c8][-2081292287][ 0]？

**Comment by lovelylain** [comment]
去不掉，修改api的dll或so可能可以。

**Comment by morganw** [comment]
你好，请问下future/ctp目录下的TraderApi.cpp MdApi.cpp 你是如何生成的，有没有生成脚本之类的？

**Comment by lovelylain** [comment]
自写py脚本把头文件转换成cython代码，然后手工修改，再用cython生成cpp
