### ISSUE TITLE
无法运行pyctp2

### ISSUE THREAD

**Issue by LeShan** [lovelylain/pyctp#42]
我的系统是ubuntu 14.04，python3.3.5

1. 准备：git clone这个工程的代码之后，先python3.3 setup.py build进行了编译，并将生成的ctp目录复制到example目录下。
2. 运行：进入pyctp2目录，运行python3.3 red.py pyctp2.sbin.md2 md_exec，显示如下内容后退出：
SaveAgent initialized
scheduler starting...
2015-03-07 08:34:56.433623 16 0 0
26704
3. 经过trace，发现是md2.py第34行：
 user.Create('%s/%s' % (INFO_PATH,mduser.name))
这句Create函数貌似找不到直接退出了？
4. 检查发在smth上的pyctp2，发现md2.py在34行是
user.RegisterSpi(md_spi)
将第1步生成的文件复制到这个版本的目录，运行这个版本，出现错误：
ImportError: cannot import name UserApiStruct

请问一下：这个工程是否支持新的pyctp2？为何md2.py跟smth上的文件不同？跑起来是否哪里还需要修改？

谢谢。

**Comment by zckm** [comment]
lovelylain的封装与pyctp2使用的封装不同，lovelylain的封装不需要RegisterSpi。如果在lovelylain的封装中使用pyctp2，需要对pyctp2做少许的修改。

**Comment by lovelylain** [comment]
@LeShan 修改版的pyctp2不支持py3只支持py2了，不过py2也没经过测试，主要是因为原版自带的那个ctp会自动把所有ApiStruct结构体的字符串在gbk与unicode之间encode/decode，但是这里用的ctypes封装的没有这么做，其实在pyctp2里按需encode/decode会更好一些。

**Comment by LeShan** [comment]
谢谢，那再在py2下跑跑试试
