### ISSUE TITLE
Python3环境下，关于bytes与str的疑问。

### ISSUE THREAD

**Issue by zckm** [lovelylain/pyctp#43]
lovelylain，你好：
       在ApiStruct.py中定义了很多常量，这些常量几乎均为str类型，如，D_Buy = '0' ，D_Sell = '1'。在封装的接口里，交易返回的实例或封装中对象接受的参数，很多属性又以bytes类型为主。

如真实交易环境在Python3.3下，OnRtnOrder返回的一个实例：
OnRtnOrder Order(BrokerID=b'1000', InvestorID=b'873912734', InstrumentID=b'rb1510', OrderRef=b'           1', UserID=b'873912734', OrderPriceType=b'2', Direction=b'1', CombOffsetFlag=b'0', CombHedgeFlag=b'1', LimitPrice=2383.0, VolumeTotalOriginal=47, TimeCondition=b'3', GTDDate=b'20150309', VolumeCondition=b'1', MinVolume=0, ContingentCondition=b'1', StopPrice=0.0, ForceCloseReason=b'0', IsAutoSuspend=0, BusinessUnit=b'0240cac', RequestID=1, OrderLocalID=b'        1665', ExchangeID=b'SHFE', ParticipantID=b'0240', ClientID=b'01773560', ExchangeInstID=b'rb1510', TraderID=b'0240cac', InstallID=1, OrderSubmitStatus=b'0', NotifySequence=0, TradingDay=b'20150309', SettlementID=1, OrderSysID=b'', OrderSource=b'0', OrderStatus=b'a', OrderType=b'0', VolumeTraded=0, VolumeTotal=47, InsertDate=b'20150306', InsertTime=b'21:25:07', ActiveTime=b'', SuspendTime=b'', UpdateTime=b'', CancelTime=b'', ActiveTraderID=b'', ClearingPartID=b'', SequenceNo=0, FrontID=1, SessionID=-1556851156, UserProductInfo=b'', StatusMsg=b'\xb1\xa8\xb5\xa5\xd2\xd1\x
cc\xe1\xbd\xbb', UserForceClose=0, ActiveUserID=b'', BrokerOrderSeq=9222, RelativeOrderSysID=b'', ZCETotalTradedVolume=0, IsSwapOrder=0) 

假设我需要在OnRtnOrder方法中判断方向，不能直接 if pOrder.Directin == D_Sell进行判断，必需首先进行str与bytes的转换，再做处理。如果使用 if pOrder.Directin == b'1'判断是没问题，可读性又不如使用D_Sell。

我知道这个不算是bug，但是不停地在str与bytes进行转换，感觉很不便。不知道封装在兼容python3、python2的情况下，封装中的常量、实例的属性是否可以统一做成str？

谢谢你。

**Comment by lovelylain** [comment]
不需要自己转换的哦，因为ApiStruct中的所有枚举字符串是要传给结构体的，所以在py2和py3都是与结构体一致的bytes类型，不写成b'xx'是因为py2.5不支持这种语法，例如
```py
Python 3.4.0 (v3.4.0:04f714765c13, Ma...tel)] on win32
Type "help", "copyright", "credits" o
>>> from ctp.futures import ApiStruct
>>> ApiStruct.D_Buy
b'0'
```
另外ApiStruct.error里每个数字对应的错误信息字符串在py2和py3都是unicode的，以便输出。

**Comment by zckm** [comment]
谢谢，我明白了。
