### ISSUE TITLE
option应该有了新的包，多了些许字段更新，原版本的不支持询价回应。

### ISSUE THREAD

**Issue by guzongyuan** [lovelylain/pyctp#46]
http://www.sfit.com.cn/DocumentDown/api/fsopt_traderapi_20150324.zip
option应该有了新的包，多了些许字段更新，原版本的不支持询价回应。

**Comment by guzongyuan** [comment]
不知道lovelylain有时间能帮忙看一下吗？

**Comment by lovelylain** [comment]
done

**Comment by guzongyuan** [comment]
多谢多谢～
