### ISSUE TITLE
Problems Running on Linux64

### ISSUE THREAD

**Issue by johngu** [lovelylain/pyctp#47]
Hello. Thanks for posting this API. I am having some trouble getting this to work on linux64. Everything compiles fine, but when I run test.py, I get the following:

`[jgu@jgulinux /projects/pyctp/build/lib.linux-x86_64-2.7]$ python test.py 
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from ctp.futures import ApiStruct, MdApi
  File "/spare/local/jgu/projects/pyctp/build/lib.linux-x86_64-2.7/ctp/futures/__init__.py", line 820, in __get__
    value = self.fget()
  File "/spare/local/jgu/projects/pyctp/build/lib.linux-x86_64-2.7/ctp/futures/__init__.py", line 834, in MdApi
    from ._MdApi import _init, MdApi; _init(ApiStruct)
ImportError: /spare/local/jgu/projects/pyctp/build/lib.linux-x86_64-2.7/ctp/futures/_MdApi.so: undefined symbol: _ZN15CThostFtdcMdApi13GetApiVersionEv`

`[jgu@jgulinux /projects/pyctp/build/lib.linux-x86_64-2.7]$ nm -g ctp/futures/_MdApi.so | grep _ZN15CThos
                 U _ZN15CThostFtdcMdApi13GetApiVersionEv
                 U _ZN15CThostFtdcMdApi15CreateFtdcMdApiEPKcbb
0000000000008bd0 W _ZN15CThostFtdcMdSpi10OnRspErrorEP22CThostFtdcRspInfoFieldib
0000000000008bb0 W _ZN15CThostFtdcMdSpi14OnRspUserLoginEP27CThostFtdcRspUserLoginFieldP22CThostFtdcRspInfoFieldib
0000000000008bc0 W _ZN15CThostFtdcMdSpi15OnRspUserLogoutEP25CThostFtdcUserLogoutFieldP22CThostFtdcRspInfoFieldib
0000000000008b80 W _ZN15CThostFtdcMdSpi16OnFrontConnectedEv
0000000000008c30 W _ZN15CThostFtdcMdSpi16OnRtnForQuoteRspEP26CThostFtdcForQuoteRspField
0000000000008ba0 W _ZN15CThostFtdcMdSpi18OnHeartBeatWarningEi
0000000000008be0 W _ZN15CThostFtdcMdSpi18OnRspSubMarketDataEP33CThostFtdcSpecificInstrumentFieldP22CThostFtdcRspInfoFieldib
0000000000008b90 W _ZN15CThostFtdcMdSpi19OnFrontDisconnectedEi
0000000000008c00 W _ZN15CThostFtdcMdSpi19OnRspSubForQuoteRspEP33CThostFtdcSpecificInstrumentFieldP22CThostFtdcRspInfoFieldib
0000000000008bf0 W _ZN15CThostFtdcMdSpi20OnRspUnSubMarketDataEP33CThostFtdcSpecificInstrumentFieldP22CThostFtdcRspInfoFieldib
0000000000008c20 W _ZN15CThostFtdcMdSpi20OnRtnDepthMarketDataEP30CThostFtdcDepthMarketDataField
0000000000008c10 W _ZN15CThostFtdcMdSpi21OnRspUnSubForQuoteRspEP33CThostFtdcSpecificInstrumentFieldP22CThostFtdcRspInfoFieldib`

It seems like in the actual compile, GetApiVersion and CreateFtdcMdApi are both undefined.

**Comment by lovelylain** [comment]
tested, no problem.
[lain@ArchLinux lib.linux-x86_64-2.7]$ md5sum ctp/futures/*.so
5bfdbc6d8f4b7dcf57d931084cd4d460  ctp/futures/libthostmduserapi.so
b955c908c8dac9603e4c66216f18ee80  ctp/futures/libthosttraderapi.so

**Comment by johngu** [comment]
Thanks for looking into this. I tried testing on another machine (Red Hat Enterprise Linux Server release 5.11) and it worked fine.  My first machine is Fedora 20, on which I had the problem.  On both machines I was using gcc 4.9.2. Rather strange problem... What Linux release are you using?

**Comment by lovelylain** [comment]
ArchLinux 3.18.6-1
