### ISSUE TITLE
新版CTP api中 已经没有 GetApiVersion()函数

### ISSUE THREAD

**Issue by sbant** [lovelylain/pyctp#48]
使用新版api vs2010编译失败，提示找不到GetApiVersion

pyctp是否需要更新，比如判断ThostFtdcMdApi.h ThostFtdcTraderApi.h中是否有GetApiVersion来条件编译

http://www.sfit.com.cn/5_2_DocumentDown.htm
2015-08-03 三个版本中都没有GetApiVersion 函数

**Comment by lovelylain** [comment]
有这个函数的版本是
>>> ctp.MdApi().GetApiVersion(), ctp.TraderApi().GetApiVersion()
('v6.3.6_20150515 14:07:46', 'v6.3.6_20150515 14:07:46')
比6.3.5版本还高

**Comment by harveywwu** [comment]
用现在的linux版本编译好像不行了，以前的版本可以。能不能fix一下

>>> from ctp.futures import MdApi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/ctp/futures/__init__.py", line 820, in __get__
    value = self.fget()
  File "/usr/local/lib/python2.7/site-packages/ctp/futures/__init__.py", line 834, in MdApi
    from ._MdApi import _init, MdApi; _init(ApiStruct)
ImportError: /usr/local/lib/python2.7/site-packages/ctp/futures/_MdApi.so: undefined symbol: _ZN15CThostFtdcMdApi13GetApiVersionEv

**Comment by lovelylain** [comment]
直接用git里面的so文件不就行了？

**Comment by harveywwu** [comment]
我就是git pull然后直接python setup.py build出错了

**Comment by lovelylain** [comment]
rm futures/ctp/*.so 后再setup.py build 编译，或者git pull到最新提交再编译
