### ISSUE TITLE
ctp回报中的乱码

### ISSUE THREAD

**Issue by shenglinqian** [lovelylain/pyctp#49]
在拿到ctp回报的时候中文显示为乱码
举例：
b'CTP:\xb1\xa8\xb5\xa5\xb4\xed\xce\xf3\xa3\xba\xb2\xbb\xd4\xca\xd0\xed\xd6\xd8\xb8\xb4\xb1\xa8\xb5\xa5'

**Comment by lovelylain** [comment]
这不是乱码，因为你用的python3，CTP结构体里所有字符串都是bytes类型的，对于提示信息，可以gbk编码解码为unicode：
>>> print(b'CTP:\xb1\xa8\xb5\xa5\xb4\xed\xce\xf3\xa3\xba\xb2\xbb\xd4\xca\xd0\xed\xd6\xd8\xb8\xb4\xb1\xa8\xb5\xa5'.decode('gbk'))
CTP:报单错误：不允许重复报单
