### ISSUE TITLE
ReqQryInstrument 如何查询全部合约

### ISSUE THREAD

**Issue by ppaanngggg** [lovelylain/pyctp#50]
请问一下，百度ReqQryInstrument这个函数全部填0是查询全部合约。但是我尝试没有成功，请问具体应该怎么使用？

我的代码是这样

self.requestID += 1
req = ApiStruct.QryInstrument()
self.ReqQryInstrument(req, self.requestID)

**Comment by ppaanngggg** [comment]
现在我是这样写的

            self.requestID += 1
            req = ApiStruct.QryInstrument()
            ctypes.memset(id(req), 0, ctypes.sizeof(req))
            print self.ReqQryInstrument(req, self.requestID)

然后core dumps，程序就崩了

**Comment by ppaanngggg** [comment]
我改成了这样就没有报错了，但是收不到行情，是因为今天周六吗？

```python
self.requestID += 1
req = ApiStruct.QryInstrument()
ctypes.memset(ctypes.addressof(req), 0, ctypes.sizeof(req))
self.ReqQryInstrument(req, self.requestID)
```

**Comment by lovelylain** [comment]
req = ApiStruct.QryInstrument() 这句代码默认就是全0的，所以你后来的改法和不memset是一样的，你最好先确认ReqQryInstrument函数是否真如你百度的填0可查全部

**Comment by ppaanngggg** [comment]
这样吗。。我也不清楚，那你是怎么查阅全部的

**Comment by Cuizi7** [comment]
经过测试，将 CTP 接口换成2016年的版本重新编译并发送 req = ApiStruct.QryInstrument() 就可以实现查询全部合约，其他版本情况暂未测试。
