### ISSUE TITLE
为什么调用SubscribeMarketData后，没有OnRtnDepthMarketData回调

### ISSUE THREAD

**Issue by gushenghua** [lovelylain/pyctp#59]
subscribe返回：
('OnRspSubMarketData:', RspInfo(ErrorID=0, ErrorMsg='No Error'), SpecificInstrument(InstrumentID='V1611'))

**Comment by zzzzv** [comment]
不停返回的是OnRtnXXXXXX，OnRsp就一次

**Comment by gushenghua** [comment]
说错了，是没有OnRtnDepthMarketData 事件

**Comment by gushenghua** [comment]
明白了，合约id只能小写，靠，ctp太坑了
