### ISSUE TITLE
ctp.stock 不回调OnRtnDepthMarketData

### ISSUE THREAD

**Issue by fulme** [lovelylain/pyctp#61]
将example/mdTest.py改成ctp.stock后OnRspSubMarketData回调了，但OnRtnDepthMarketData一直没有调用。行情订阅改成：self.SubscribeMarketData([b'000016'], b'SSE')   不知道是我的写法有问题还是stock接口不能使用了呢，麻烦啦！

**Comment by lovelylain** [comment]
换小写试试 issue#59
