### ISSUE TITLE
CTP外盘api

### ISSUE THREAD

**Issue by yukinjie** [lovelylain/pyctp#63]
非常感谢你的接口封装； 不知道可不可以封装一份ctp 外盘的python接口呢。py程序应该是自动解析的吧。

**Comment by yukinjie** [comment]
这是api c++接口 http://pan.baidu.com/s/1skIFa8H

**Comment by ppaanngggg** [comment]
请问一下，这个api是哪里找到的啊，可以做哪些？什么公司可以开户？

**Comment by yukinjie** [comment]
上期发布的；主要做国外期货交易，对接的CME交易所。 目前好像横华期货有开户。

**Comment by ppaanngggg** [comment]
我浏览了一下，好像和国内的没什么区别的啊，你确定靠谱吗
