### ISSUE TITLE
pyctp的封装细节求指导

### ISSUE THREAD

**Issue by 345161974** [lovelylain/pyctp#65]
因为学习Cython（主要来封装LTS最新的库），偶然间发现lovelylain的开源项目，非常感谢这么高质量的封装，并且开源。

学习原作者的封装技巧时，个人觉得对于mdspi类的回调函数这块lovelylain封装技巧运用的非常棒。我也打算采取该方法。

但是在学习lovelylain的源码中，我有些疑问，冒昧请教，**如果不方便回应也没事，权当留言支持下作者**。

* Cython代码中的pxd应该都是自动生成的，敢问下用的哪个自动生成工具？我看到Cython的github wiki的AutoPxd中提到了很多中自动封装工具，不晓得笔者用的哪个？ 

* 对于mdspi类的回调函数中参数封装问题，我个人知识水平，理解下来难度很高，我也思考了很久，并不是随便发问，希望笔者能略加指导，辅助我理解下：

ApiStruct.py文件中
```
def _init():
    import re, sys
    from ctypes import c_char, c_short, c_int, c_double, Structure
    G = globals(); del G['_init']; T = G.pop('T'); Base = G.pop('BaseStruct')
    match = re.compile(r'(\w+)\[(\d+)\]').match
    D = {'char':c_char, 'short':c_short, 'int':c_int, 'double':c_double}
    for k,v in T.items():
        if v not in D:
            m = match(v).groups(); D[v] = D[m[0]] * int(m[1])
        T[k] = D[v]
    ...
```
这个函数的主要功能是做什么用？我看到ApiStruct.py文件中大部分变量应该是填充cUserApiDataType.pxd中的各种变量，枚举值，然而最后的这个_init()函数看不大懂；

* 封装在MdApi.pyx中的回调函数转发
```
cdef extern int MdSpi_OnRtnDepthMarketData(self, CDepthMarketDataField *pDepthMarketData) except -1:
    self.OnRtnDepthMarketData(None if pDepthMarketData is NULL else ApiStruct_DepthMarketData(<size_t>pDepthMarketData))
    return 0
```
此段代码中的为什么不是直接将CDepthMarketDataField *pDepthMarketData传入self对象，而是通过ApiStruct_DepthMarketData(<size_t>pDepthMarketData)再次转换了一下？不是特别理解

* 对于MdApi.pyx中一段函数主要目的
MdApi.pyx文件中一开头便定义了各种函数
```
...
CSetAttr(Xmod, _init_method.ml_name, PyCFunction_NewEx(&_init_method, NULL, XCGetAttr(Xmod, S___name__)))
...
```
这段函数主要的作用是什么呢？

冒昧提出以上问题，肯请赐教，thx!

**Comment by lovelylain** [comment]
Cython代码生成是自己写的Python脚本，基本全靠re匹配，很挫，生成后还得修改很多地方。

`__init__.py`和`ApiStruct.py`的很多处理都是为了能让IDE能自动提示才写成那样的，实用第一：
ctp的两个so文件链接放到同一个c模块会在退出时出现double free异常，所以分别对应一个c模块；
ctp的两个so文件的32位好像是有问题，其中一个so导入就挂，所以用了lazy_import的方法（其实没啥必要）；
设想__init__.py里就3行代码
```py
from . import ApiStruct
from ._MdApi import MdApi
from ._TraderApi import TraderApi
```
除非去看ctp官方的头文件，否则根本不知道MdApi、TraderApi提供了哪些函数、需要哪些回调、每个函数原型是什么样的，所以__init__.py就长这样了，方便IDE自动补全；
`ApiStruct.py`同理，设想都是直接继承`ctypes.Structure`，IDE没法给你提示每个结构有哪些字段、每个字段是什么类型，于是写了个伪类，通过这个伪类可以方便IDE自动提示，_init执行后实际还是继承`ctypes.Structure`的类。

CDepthMarketDataField *pDepthMarketData是一个c指针，是没法直接传入python函数的，需要传入继承`ctypes.Structure`的对象，也就是`None if pDepthMarketData is NULL else DepthMarketData.from_address(<size_t>pDepthMarketData)`。

洁癖！避免cython对只用一次的字符串给我生成全局变量(⊙﹏⊙)b

**Comment by 345161974** [comment]
@lovelylain 
> 没想到lovelylain为了实现IDE自动补全做了那么多辛苦的工作！

> 参考您的封装技巧，我在自己封装的LTS代码里也采用了相同的回调函数传递机制，不过对于PyObject对象里的回调函数里结构体参数的转发，我用的比较简单的写法了，直接在内部填充dict数据，完成填充直接转发出去，测试实验也都是pass的：
```
cdef extern int MdSpi_OnRspUserLogin(self, CSecurityFtdcRspUserLoginField *pRspUserLogin, CSecurityFtdcRspInfoField *pRspInfo, int nRequestID, cbool bIsLast) except -1:
    dict_pRspUserLogin = {}
    dict_pRspUserLogin['BrokerID'] = pRspUserLogin.BrokerID
    dict_pRspUserLogin['UserID'] = pRspUserLogin.UserID
    dict_pRspUserLogin['FrontID'] = pRspUserLogin.FrontID
    dict_pRspUserLogin['LoginTime'] = pRspUserLogin.LoginTime
    dict_pRspUserLogin['MaxOrderRef'] = pRspUserLogin.MaxOrderRef
    dict_pRspUserLogin['SessionID'] = pRspUserLogin.SessionID

    dict_pRspInfo = {}
    dict_pRspInfo['ErrorID'] = pRspInfo.ErrorID
    dict_pRspInfo['ErrorMsg'] = pRspInfo.ErrorMsg

    self.OnRspUserLogin(dict_pRspUserLogin, dict_pRspInfo, nRequestID, bIsLast)
    return 0
```
虽然不高大上，但是已经实现目的。

* 最后还是非常感谢lovelylain牛逼的封装，ths！
* 该issue可以close了
