### ISSUE TITLE
python3.6无法撤单

### ISSUE THREAD

**Issue by njuxukai** [lovelylain/pyctp#69]
RtnOrder委托信息(BrokerID=b'2318', InvestorID=b'00002857', InstrumentID=b'IF1801', OrderRef=b'3', UserID=b'00002857', OrderPriceType=b'2', Direction=b'0', CombOffsetFlag=b'0', CombHedgeFlag=b'1', LimitPrice=4030.0, VolumeTotalOriginal=3, TimeCondition=b'3', GTDDate=b'', VolumeCondition=b'1', MinVolume=0, ContingentCondition=b'1', StopPrice=0.0, ForceCloseReason=b'0', IsAutoSuspend=0, BusinessUnit=b'231801', RequestID=5, OrderLocalID=b'         154', ExchangeID=b'CFFEX', ParticipantID=b'2318', ClientID=b'01427499', ExchangeInstID=b'IF1801', TraderID=b'231801', InstallID=1, OrderSubmitStatus=b'3', NotifySequence=1, TradingDay=b'20171222', SettlementID=1, OrderSysID=b'      405160', OrderSource=b'0', OrderStatus=b'3', OrderType=b'0', VolumeTraded=0, VolumeTotal=3, InsertDate=b'20171222', InsertTime=b'13:53:53', ActiveTime=b'', SuspendTime=b'', UpdateTime=b'', CancelTime=b'', ActiveTraderID=b'231801', ClearingPartID=b'2042', SequenceNo=373, FrontID=1, SessionID=-1721799859, UserProductInfo=b'', StatusMsg=b'\xce\xb4\xb3\xc9\xbd\xbb', UserForceClose=0, ActiveUserID=b'', BrokerOrderSeq=153, RelativeOrderSysID=b'', ZCETotalTradedVolume=0, IsSwapOrder=0)
试图撤单，使用
OrderAction(BrokerID=b'2318', InvestorID=b'00002857', OrderActionRef=0, OrderRef=b'3', RequestID=0, FrontID=1, SessionID=-1721799859, ExchangeID=b'', OrderSysID=b'', ActionFlag=b'0', LimitPrice=0.0, VolumeChange=0, ActionDate=b'', ActionTime=b'', TraderID=b'', InstallID=0, OrderLocalID=b'', ActionLocalID=b'', ParticipantID=b'', ClientID=b'', BusinessUnit=b'', OrderActionStatus=b'a', UserID=b'', StatusMsg=b'', InstrumentID=b'IF1801')

返回   [25][CTP:撤单找不到相应报单]

**Comment by njuxukai** [comment]
加上了 ExchangeID+OrderSysID 能够撤单成功。
但在我设计的交易场景下，委托时得到的FrontID+SessionID+OrderRef 是作为我委托的主键存放在数据库及内存的。后续RtnOrder得到的ExchangeID+OrderSysID只是缓存用来关联成交回报。 我不想撤单依赖于这个缓存机制，麻烦作者看下是什么问题

**Comment by lovelylain** [comment]
完全只是一个ctp api的封装，具体要传哪些字段才能操作成功是ctp api本身决定的
